### ISSUE TITLE
expo.d.ts status

### ISSUE THREAD

**Issue by kbrandwijk** [janaagaard75/expo-and-typescript#2]
A search for Expo typings led me here. What is the status of your expo typings? How can I help?

**Comment by janaagaard75** [comment]
The status is, unfortunately, that's most of the APIs in the Expo SDK still need to be tested, and while some of the APIs probably work with the current definitions, I think that most of them need a little tweaking. (Example: It's no longer okay use `void` as the props or the state of a React component.)

If you want to help then you can pick one of the APIs, make a small test screen verifying it, and the create a pull request once it works. That would be greatly appreciated.

**Comment by kbrandwijk** [comment]
I started using it in my current project and I will tweak what I come across. When it's done, I'll do a more structured test with the isolated APIs, and start adding screens here.

**Comment by janaagaard75** [comment]
Sounds great. 👍
