### ISSUE TITLE
error TS2339: Property 'create' does not exist on type 'typeof Sound'.

### ISSUE THREAD

**Issue by dooboolab** [janaagaard75/expo-and-typescript#3]
```typescript
const { sound } = await Audio.Sound.create(
    { uri: this.listenFile },
    {
        shouldPlay: true,
        progressUpdateIntervalMillis: 500,
    },
);
```

How can I resolve
error TS2339: Property 'create' does not exist on type 'typeof Sound'.
error when I run tsc?

![image](https://user-images.githubusercontent.com/27461460/32954103-806e7bf4-cbf5-11e7-8135-876049d9fe73.png)

**Comment by janaagaard75** [comment]
Try adding this to the Sound class:

```typescript
public static create(
  source: any, initialStatus: any,
  onPlaybackStatusUpdate?: Function,
  downloadFirst?: boolean
): Promise<{ sound: Sound, status: any }>
```

Note that I haven't testet this yet, and ideally the `any` should be replaced with something more specific, but with a bit a luck, this would allow you to continue.

If the above doesn't work, you should be able to circumvent the type error by casting `create` to `any`. It would look something like this, but I am not sure the syntax blow is 100 % correct.

```typescript
const { sound } = await (Audio.Sound.create as any)(
  { uri: this.listenFile },
  {
    shouldPlay: true,
    progressUpdateIntervalMillis: 500,
  },
);
```

**Comment by janaagaard75** [comment]
I have just updated the Audio API in `expo.d.ts`. I haven't had time to test it yet, so let me know if this fixes your issue.

**Comment by janaagaard75** [comment]
I've added a screen testing `Audio.Sound.create`, so now I'm quite confident it works, so I'm closing this issue.
