### ISSUE TITLE
check-types: should I pass a watch flag?

### ISSUE THREAD

**Issue by peterpme** [janaagaard75/expo-and-typescript#32]
Hello!

Thank you for the incredible project. Should I be passing in `--watch` flag for `check-types` if I want to constantly be running this in my terminal?

I don't use vscode and I'm new to typescript, but would like to give this all shot. Please let me know what you think is best

**Comment by janaagaard75** [comment]
Yes, using the `--watch` switch should work fine, so depending on weather you're using Yarn or npm the command would be one of these two. (It's an older npm version 6.4.1 that I have installed, so you might be able to use a shorter syntax if you have a newer version installed.)

    yarn check-types --watch
    npm run check-types -- --watch

That being said, I can warmly recommend Visual Studio Code, so I would recommend that you also give that editor a try when exploring this code base.

**Comment by peterpme** [comment]
Thank you! I appreciate the help :)
