### ISSUE TITLE
No errors being displayed in VS Code

### ISSUE THREAD

**Issue by Feijo** [janaagaard75/expo-and-typescript#36]
Just cloned the repo, and no matter what I do, it doesn't display any errors at all. Extension TSLint is installed. Other react projects work just fine. 

![image](https://user-images.githubusercontent.com/1585710/60141606-26d37d00-980a-11e9-981c-3159a0ae9f05.png)

**Comment by Feijo** [comment]
Restarted the computer and the problem seems to be gone.

**Comment by janaagaard75** [comment]
Note that the building the code does not chech the tyoe definitions, because that’s how Babel works. This supposedly makes the build a lot faster, but it’s not noticeable with such a small project.

Run `yarn check-types` to validate the TypeScript types.
