### ISSUE TITLE
Issue loading the project for first time.

### ISSUE THREAD

**Issue by diegolaciar** [janaagaard75/expo-and-typescript#46]
Hi @janaagaard75 ,

I'm trying to load the project for first time in Android device as I use to do with other projects but I got this issues that I want let you know. I don' t know if it's just me of something related with the last updates of the project & expo version.

<img width="1145" alt="Screen Shot 2020-01-06 at 14 01 49" src="https://user-images.githubusercontent.com/608122/71834120-353e0380-308d-11ea-831e-48d6394c37ce.png">

Regards,
Diego

**Comment by diegolaciar** [comment]
For the first issue I added the spash.png into assets directory.

for the second issue I cleared react native cache with option

-c, --clear           Clear the React Native packager cache

**Comment by janaagaard75** [comment]
Thanks a lot for reporting this, Diego.

Expo's default name is `splash.png`, but I think the name `splash-screen.png` is better. The path for the image is defined in [`app.json`](https://github.com/janaagaard75/expo-and-typescript/blob/master/app.json), so we might have stumbled upon an issue in Expo.

Glad you were able to resolve the debuggerWorker issue by clearing the cache. I don't think I can do anything about this, so I hope that it just a rare exception.

I'll keep this issue open, and try to recreate the issue with missing splash screen image.

**Comment by janaagaard75** [comment]
I couldn't reproduce the issue, but I added a troubleshooting section to the readme with your tip.
